### ISSUE TITLE
only a grey window displayed on Mac

### ISSUE THREAD

**Issue by klauspdoll** [ebassi/glarea-example#10]
This example works for me on openSUSE15.5.

I would however be interested on a working version for Mac also.

Some time ago, I could build it on a Mac Monterey, and it was okay (shader version 410 was necessary, as reported in  https://github.com/ebassi/glarea-example/issues/9). Most likely because of an update which happened meanwhile when doing `brew install glm` (glm was required by some code using the OpenGL core profile), it now still compiles, but shows a grey window only. On an older MacBook  I have access to (with renderer Intel Iris Pro OpenGL Engine), it is the same (grey window); also other people reported a grey window on fairly new Mac M1 .

Is there any workaround known for this?

![glarea-Mac-Monterey](https://github.com/ebassi/glarea-example/assets/109160884/dcf6cf2a-dc65-4944-b06c-86928eb73dab)

**Comment by jason5122** [comment]
I'm also experiencing this issue!

M2 Max, macOS 14.3

**Comment by ebassi** [comment]
You should file an issue on the [GTK issue tracker](https://gitlab.gnome.org/GNOME/gtk/-/issues).
