### ISSUE TITLE
Not starting up the application and provide a glade example please.

### ISSUE THREAD

**Issue by grotius-cnc** [ebassi/glarea-example#5]
Hi, nice example.
To start this up in debian 9 it's a bit difficult. I solved starting the application by typing in terminal : **MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450 ./glarea**
Please add this start option to your readme file.

**Comment by grotius-cnc** [comment]
Can you provide a example how to start up the application with a glade gui instead of ui written? I am searching but cannot find a example.

**Comment by ebassi** [comment]
> To start this up in debian 9 it's a bit difficult. I solved starting the application by typing in terminal : **MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450 ./glarea**
> Please add this start option to your readme file.

That's a Debian-only issue, so I'm not really going to add it to the README.

> Can you provide a example how to start up the application with a glade gui instead of ui written?

I don't know what "start up the application with a glade gui" means. This is an example of how to write a GL application using GTK 3; the example comes with its own UI.
