### ISSUE TITLE
incorrect types for GL objects

### ISSUE THREAD

**Issue by claudeha** [ebassi/glarea-example#6]
The code uses `guint` when it should be using `GLuint` or `GLint`:

https://github.com/ebassi/glarea-example/blob/c5573a0e92558d23709335dbe00dab3d62dc710f/glarea-app-window.c#L30-L35

That it happens to work may just be an (un)lucky accident.

**Comment by ebassi** [comment]
`GLuint` and `GLint` are typedefs to `unsigned int` and `int`, respectively; the same applies to `guint` and `gint` from GLib.
