### ISSUE TITLE
Enhancement: Multi-sampling

### ISSUE THREAD

**Issue by neurolabusc** [ebassi/glarea-example#7]
This tutorial was really helpful in helping me port GTK2 OpenGL applications to GTK3. However, the resulting projects do not look as nice, as it is unclear how to enable multisampling with GTK3. This is best seen in high contrast edges, such as white on black. Below on the left is your GTK3 project with the background set to black and the top vertex set to white. Note the jagged appearance of the right triangle. The left is what is generated with GTK2 using x4 multisampling: the aliasing of the edges is much nicer, with partial volume represented by gray. Is there any way to enable multisampling with GTK3 OpenGL?

![gtk3_vs_gtk2](https://user-images.githubusercontent.com/8930807/70804279-14cba380-1d84-11ea-9429-5aec42b5cacb.png)

**Comment by ebassi** [comment]
You should ask questions about GTK on the [GTK support forum](https://discourse.gnome.org/tag/gtk).

Multisampling needs to be enabled when setting up the GL context, and then enabled when rendering on the FBO; you may need an intermediate FBO for that, since GTK3 does not expose API for it.
